# Generated by Django 2.0.3 on 2018-06-10 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='udpated_by',
            new_name='updated_by',
        ),
    ]
